version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    groups:
      bundler-version:
        applies-to: version-updates
        patterns: ["*"]
      bundler-security:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
