inherit_from:
  - .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
